[tool.poetry]
name = "gotrue"
version = "0.5.4"
description = "Python Client Library for GoTrue"
authors = ["Joel Lee <joel@joellee.org>"]
homepage = "https://github.com/supabase-community/gotrue-py"
repository = "https://github.com/supabase-community/gotrue-py"
documentation = "https://github.com/supabase-community/gotrue-py"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.23.0"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
flake8 = "^5.0.4"
black = "^22.6.0"
isort = "^5.10.1"
pre-commit = "^2.20.0"
pytest-cov = "^3.0.0"
pytest-depends = "^1.0.1"
pytest-asyncio = "^0.19.0"
Faker = "^14.1.1"
unasync-cli = "^0.0.9"
python-semantic-release = "^7.31.4"

[tool.semantic_release]
version_variable = "gotrue/__init__.py:__version__"
version_toml = "pyproject.toml:tool.poetry.version"
major_on_zero = false
commit_subject = "chore(release): bump version to v{version}"
build_command = "curl -sSL https://install.python-poetry.org | python - && export PATH=\"/github/home/.local/bin:$PATH\" && poetry install && poetry build"
upload_to_repository = true
branch = "main"
changelog_components = "semantic_release.changelog.changelog_headers,semantic_release.changelog.compare_url"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
