[tool.poetry]
name = "gotrue"
version = "1.0.2"
description = "Python Client Library for GoTrue"
authors = ["Joel Lee <joel@joellee.org>"]
homepage = "https://github.com/supabase-community/gotrue-py"
repository = "https://github.com/supabase-community/gotrue-py"
documentation = "https://github.com/supabase-community/gotrue-py"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.8"
httpx = ">=0.23,<0.25"
pydantic = "^1.10.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
flake8 = "^5.0.4"
black = "^23.3.0"
isort = "^5.12.0"
pre-commit = "^3.2.2"
pytest-cov = "^4.0.0"
pytest-depends = "^1.0.1"
pytest-asyncio = "^0.21.1"
Faker = "^18.3.1"
unasync-cli = "^0.0.9"
python-semantic-release = "^7.34.6"

[tool.poetry.group.dev.dependencies]
pygithub = "^1.57"

[tool.semantic_release]
version_variable = "gotrue/__init__.py:__version__"
version_toml = "pyproject.toml:tool.poetry.version"
major_on_zero = false
commit_subject = "chore(release): bump version to v{version}"
build_command = "curl -sSL https://install.python-poetry.org | python - && export PATH=\"/github/home/.local/bin:$PATH\" && poetry install && poetry build"
upload_to_repository = true
branch = "main"
changelog_components = "semantic_release.changelog.changelog_headers,semantic_release.changelog.compare_url"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
