[tool.poetry]
name = "gotrue"
version = "2.2.0"
description = "Python Client Library for GoTrue"
authors = ["Joel Lee <joel@joellee.org>"]
homepage = "https://github.com/supabase-community/gotrue-py"
repository = "https://github.com/supabase-community/gotrue-py"
documentation = "https://github.com/supabase-community/gotrue-py"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.8"
httpx = ">=0.23,<0.26"
pydantic = ">=1.10,<3"

[tool.poetry.dev-dependencies]
pytest = "^7.4.2"
flake8 = "^5.0.4"
black = "^23.9.1"
isort = "^5.12.0"
pre-commit = "^3.4.0"
pytest-cov = "^4.0.0"
pytest-depends = "^1.0.1"
pytest-asyncio = "^0.21.1"
Faker = "^22.0.0"
unasync-cli = "^0.0.9"
python-semantic-release = "^8.1.1"

[tool.poetry.group.dev.dependencies]
pygithub = ">=1.57,<3.0"

[tool.semantic_release]
version_variables = ["gotrue/__init__.py:__version__"]
version_toml = ["pyproject.toml:tool.poetry.version"]
major_on_zero = false
commit_message = "chore(release): bump version to v{version}"
build_command = "curl -sSL https://install.python-poetry.org | python - && export PATH=\"/github/home/.local/bin:$PATH\" && poetry install && poetry build"
upload_to_vcs_release = true
branch = "main"
changelog_components = "semantic_release.changelog.changelog_headers,semantic_release.changelog.compare_url"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
